### ISSUE TITLE
Broken in Ember 2.8

### ISSUE THREAD

**Issue by alexgb** [AltSchool/ember-cli-react#28]
PR #26 seems to have broken tests in Ember 2.8. This is because Ember 2.8 inserts an html comment inside an empty component, which means that our test that expects no child nodes actually has a single child of type comment.

I think the solution here would be to ensure that we only pass children to the react component if there are more than 0 non comment child nodes.

**Comment by alexgb** [comment]
FYI @pswai

**Comment by pswai** [comment]
@alexgb thanks for checking! I wonder why it didn't break CI tests. We need to add Ember 2.8 to ember-try i think

**Comment by pswai** [comment]
@alexgb I think i will upgrade Ember-CLI all the way to 3.2 to make sure we cover more versions

**Comment by alexgb** [comment]
It did break in the circle tests once merged: https://circleci.com/gh/AltSchool/ember-cli-react/59. Not sure why it didn't break in the PR branch.

**Comment by pswai** [comment]
@alexgb I think that's because of the `ember-try.js` config file, 2.8 was not there.

I have start working on it, I think we can't simply just filter out all comment nodes because Ember might depend on those nodes to do something. What we can do is to check whether the component is in block form, if it is not then we can just don't define any children. If it is in block form then the component should expect children in the first place anyway. What do you think?

**Comment by alexgb** [comment]
@pswai yep that seems like a better approach and probably more efficient than the existing implementation that checks NodeList.length, since I believe that the length property there is lazy.

**Comment by pswai** [comment]
@alexgb I tried various way to figure out whether a component is in block form but it seems complicated. There is this `hasBlock` property but only available in template. Also, checking `childViews` is not reliable since Glimmer as it will be out of sync. Do you know any other way to get that information?

**Comment by alexgb** [comment]
@pswai I wonder if we can move this logic to the `react-component` template somehow:

```handlebars
{{#if (or hasBlock children)}}
  {{react-component "yield-wrapper" key=elementId children=children}}
{{/if}}
```

**Comment by pswai** [comment]
I have tried that but apparently the template was not picked up, probably we need to update resolver.

However, I have some concerns with moving it to template:
- We are extracting DOM nodes to be children in JS, so the `children` property is incorrect
- We are creating `yield-wrapper` indirectly (via Ember), so there will be an extra layer of `div`
- It limits us to modify things later (we need to create helpers, etc)

I think getting the symbol `HAS_BLOCK` and then read the value from component instance should be the best way to go. :)
